version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${TARGET:-dev}
    env_file:
      - ./.env
    command: ['/entrypoint.sh']
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - filestorage

  filestorage:
    image: petrishutin/filestorage:latest
    env_file:
      - ./.env
    command: ['/entrypoint.sh']
    ports:
      - "8001:8000"
    volumes:
      - './.local_file_storage:/var/lib/local_file_storage'

  mongo:
    image: mongo:latest
    ports:
      - "27117:27017"
    env_file:
      - ./.env
