version: '3.8'
services:
  app:
    build: .
    env_file:
      - ./.env
    command: /entrypoint.sh
    ports:
      - "8100:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27117:27017"
    env_file:
      - ./.env

