version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${TARGET:-dev}
    command: [ '/entrypoint.sh' ]
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - filestorage

  filestorage:
    image: petrishutin/filestorage:latest
    environment:
      - FILE_STORAGE_TYPE=LocalFileStorage
      - BUCKETS=test-1,test-2
    command: [ '/entrypoint.sh' ]
    ports:
      - "8001:8000"
    volumes:
      - './.local_file_storage:/var/lib/local_file_storage'
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27117:27017"
    volumes:
      - './.mongo:/var/lib/mongo'