apiVersion: v1
kind: Pod
metadata:
  name: ub
  namespace: default
  labels:
    app: ub
spec:
  containers:
  - image: ubuntu
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always