apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-1  # имя деплоймента
  namespace: august  # принадлежность к пространству имен
spec:  # спецификация деплоймента
  selector:  # (слектор как его найти)
    matchLabels:
      app: todo-app
  replicas: 1  # Количество реплик. В промышленной среде 2 и более
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: test-app-1
          image: petrishutin/todo-app:latest
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-service-1
  namespace: august
  labels:
    app: todo-app-service-label # метка для слектора (Каждый объект может в кубе может иметь совою метку). Это собственная метка сервися а не метка на которую он смотрит.
spec:
  ports:
    - name: http-todo-app # имя порта
      port: 8000 # порт на котором будет доступен сервис
      targetPort: 8000 # порт контейнера (приложения)
  selector:
    app: todo-app # А вот это уже метка соответсвие которой будет проверять сервис из множества подов в неймспейсе
#          volumeMounts: # монтирование созданной ниже абстракции по указанному пути
#            - name: nginx-index-file
#              mountPath: /usr/share/nginx/html/
#      volumes: # это создание абстракции которая заберет документ из конфигмапа

---